#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Rion Miura
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
i = 0
ave = 0
for line in sys.stdin:
    try:
       ans += int(line)
       i += 1       
    except:
       ans += float(line)
       i += 1

ave = ans / i
print(ave)
