#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Rion Miura
# SPDX-License-Identifier: BSD-3-Clause

import sys

add = 0
i = 0
ans = 0
for line in sys.stdin:
    try:
       add += int(line)
       i += 1       
    except:
       add += float(line)
       i += 1

ans = add / i
print(ans)
